#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  4 09:51:31 2024

@author: harrisbolus
"""
from typing import Union

_refseq_prefixes = {
    'AC_': ('Refseq', 'Genomic - Complete genomic molecule, usually alternate assembly'),
    'NC_': ('Refseq', 'Genomic - Complete genomic molecule, usually reference assembly'),
    'NG_': ('Refseq', 'Genomic - Incomplete genomic region'),
    'NT_': ('Refseq', 'Genomic - Contig or scaffold, clone-based or WGSa'),
    'NW_': ('Refseq', 'Genomic - Contig or scaffold, primarily WGSa'),
    'NZ_': ('Refseq', 'Genomic - Complete genomes and unfinished WGS data'),
    'NM_': ('Refseq', 'mRNA - Protein-coding transcripts (usually curated)'),
    'NR_': ('Refseq', 'RNA - Non-protein-coding transcripts'),
    'XM_': ('Refseq', 'mRNA - Predicted model protein-coding transcript'),
    'XR_': ('Refseq', 'RNA - Predicted model non-protein-coding transcript'),
    'AP_': ('Refseq', 'Protein - Annotated on AC_ alternate assembly'),
    'NP_': ('Refseq', 'Protein - Associated with an NM_ or NC_ accession'),
    'YP_': ('Refseq', 'Protein - Annotated on genomic molecules without an instantiated transcript record'),
    'XP_': ('Refseq', 'Protein - Predicted model, associated with an XM_ accession'),
    'WP_': ('Refseq', 'Protein - Non-redundant across multiple strains and species')
    }

_simple_INDSC_prefixes = {
    'A': ('EBI', 'Patent'),
    'AA': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'AB': ('DDBJ', 'Direct submissions'),
    'AC': ('NCBI', 'HTG (genomic DNA)'),
    'AD': ('NCBI', 'Seqs received at GSDB (Genome Sequence Database)'),
    'AE': ('NCBI', 'Genome projects'),
    'AF': ('NCBI', 'Direct submissions'),
    'AG': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'AH': ('NCBI', 'Direct submissions segsets'),
    'AI': ('NCBI', 'Other projects'),
    'AJ': ('EBI', 'Direct submissions'),
    'AK': ('DDBJ', 'HTC (cDNA)'),
    'AL': ('EBI', 'Genome projects'),
    'AM': ('EBI', 'Direct submissions'),
    'AN': ('EBI', 'scaffold/CON'),
    'AP': ('DDBJ', 'Genome projects'),
    'AQ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'AR': ('NCBI', 'Patent'),
    'AS': ('NCBI', 'Other projects'),
    'AT': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'AU': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'AV': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'AW': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'AX': ('EBI', 'Patent'),
    'AY': ('NCBI', 'Direct submissions'),
    'AZ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'B': ('NCBI', 'GSS (previously DDBJ)'),
    'BA': ('DDBJ', 'scaffold/CON'),
    'BB': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BC': ('NCBI', 'cDNA project'),
    'BD': ('DDBJ', 'Patent'),
    'BE': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BF': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BG': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BH': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'BI': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BJ': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BK': ('NCBI', 'TPA (third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'BL': ('NCBI', 'TPA CON (constructed third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'BM': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BN': ('EBI', 'TPA (third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'BP': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BQ': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BR': ('DDBJ', 'TPA (third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'BS': ('DDBJ', 'Genome projects'),
    'BT': ('NCBI', 'FLI_cDNA'),
    'BU': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BV': ('NCBI', 'STS (Sequence Tagged Sites)'),
    'BW': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BX': ('EBI', 'Genome projects'),
    'BY': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'BZ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'C': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CA': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CB': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CC': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'CD': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CE': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'CF': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CG': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'CH': ('NCBI', 'scaffold/CON'),
    'CI': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CJ': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CK': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CL': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'CM': ('NCBI', 'scaffold/CON'),
    'CN': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CO': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CP': ('NCBI', 'Genome projects'),
    'CQ': ('EBI', 'Patent'),
    'CR': ('EBI', 'Genome projects'),
    'CS': ('EBI', 'Patent'),
    'CT': ('EBI', 'Genome projects'),
    'CU': ('EBI', 'Genome projects'),
    'CV': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CW': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'CX': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'CY': ('NCBI', 'Influenza Virus Genome'),
    'CZ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'D': ('DDBJ', 'Direct submissions'),
    'DA': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DB': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DC': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DD': ('DDBJ', 'Patent'),
    'DE': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'DF': ('DDBJ', 'scaffold/CON'),
    'DG': ('DDBJ', 'scaffold/CON'),
    'DH': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'DI': ('DDBJ', 'Patent KIPO'),
    'DJ': ('DDBJ', 'Patent JPO'),
    'DK': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DL': ('DDBJ', 'Patent JPO'),
    'DM': ('DDBJ', 'Patent JPO'),
    'DN': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DO': ('NCBI', 'not used'),
    'DP': ('NCBI', 'HTG scaffolds (CONs)'),
    'DQ': ('NCBI', 'Direct submissions'),
    'DR': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DRA': ('DDBJ', 'SRA (Sequence Read Archive) submissions'),
    'DRP': ('DDBJ', 'SRA (Sequence Read Archive) sample'),
    'DRR': ('DDBJ', 'SRA (Sequence Read Archive) runs'),
    'DRX': ('DDBJ', 'SRA (Sequence Read Archive) experiment'),
    'DRZ': ('DDBJ', 'SRA (Sequence Read Archive) analysis object'),
    'DS': ('NCBI', 'scaffold/CON'),
    'DT': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DU': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'DV': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DW': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DX': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'DY': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'DZ': ('NCBI', 'Patent'),
    'E': ('DDBJ', 'Patent'),
    'EA': ('NCBI', 'Patent'),
    'EB': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EC': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'ED': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'EE': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EF': ('NCBI', 'Direct submissions'),
    'EG': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EH': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EI': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'EJ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'EK': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'EL': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EM': ('NCBI', 'scaffold/CON'),
    'EN': ('NCBI', 'scaffold/CON'),
    'EO': ('NCBI', 'not used'),
    'EP': ('NCBI', 'scaffold/CON'),
    'EQ': ('NCBI', 'scaffold/CON'),
    'ER': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'ERA': ('EBI', 'SRA (Sequence Read Archive) submissions'),
    'ERP': ('EBI', 'SRA (Sequence Read Archive) sample'),
    'ERR': ('EBI', 'SRA (Sequence Read Archive) runs'),
    'ERX': ('EBI', 'SRA (Sequence Read Archive) experiment'),
    'ERZ': ('EBI', 'SRA (Sequence Read Archive) analysis object'),
    'ES': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'ET': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'EU': ('NCBI', 'Direct submissions'),
    'EV': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EW': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EX': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EY': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'EZ': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'F': ('EBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FA': ('NCBI', 'scaffold/CON (pseudomolecules)'),
    'FB': ('EBI', 'Patent'),
    'FC': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FD': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FE': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FF': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FG': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FH': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'FI': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'FJ': ('NCBI', 'Direct submissions'),
    'FK': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FL': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FM': ('EBI', 'Direct submissions'),
    'FN': ('EBI', 'Direct submissions'),
    'FO': ('EBI', 'Direct submissions'),
    'FP': ('EBI', 'Direct submissions'),
    'FQ': ('EBI', 'Direct submissions'),
    'FR': ('EBI', 'Direct submissions'),
    'FS': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FT': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'FU': ('DDBJ', 'Patent'),
    'FV': ('DDBJ', 'Patent JPO'),
    'FW': ('DDBJ', 'Patent'),
    'FX': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'FY': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'FZ': ('DDBJ', 'Patent'),
    'G': ('NCBI', 'STS (Sequence Tagged Sites)'),
    'GA': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'GB': ('DDBJ', 'Patent JPO'),
    'GC': ('NCBI', 'Patent'),
    'GD': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GE': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GF': ('NCBI', 'STS (Sequence Tagged Sites)'),
    'GG': ('NCBI', 'scaffold/CON'),
    'GH': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GI': ('NCBI', 'not used'),
    'GJ': ('NCBI', 'TPA CON (constructed third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'GK': ('NCBI', 'TPA CON (WGS chromosomes)'),
    'GL': ('NCBI', 'scaffold/CON'),
    'GM': ('EBI', 'Patent'),
    'GN': ('EBI', 'Patent'),
    'GO': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GP': ('NCBI', 'Patent'),
    'GQ': ('NCBI', 'Direct submissions'),
    'GR': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GS': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'GT': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GU': ('NCBI', 'Direct submissions'),
    'GV': ('NCBI', 'Patent'),
    'GW': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'GX': ('NCBI', 'Patent'),
    'GY': ('NCBI', 'Patent'),
    'GZ': ('NCBI', 'Patent'),
    'H': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'HA': ('EBI', 'Patent'),
    'HB': ('EBI', 'Patent'),
    'HC': ('EBI', 'Patent'),
    'HD': ('EBI', 'Patent'),
    'HE': ('EBI', 'Direct submissions'),
    'HF': ('EBI', 'Direct submissions'),
    'HG': ('EBI', 'Direct submissions'),
    'HH': ('EBI', 'Patent'),
    'HI': ('EBI', 'Patent'),
    'HJ': ('NCBI', 'Patent'),
    'HK': ('NCBI', 'Patent'),
    'HL': ('NCBI', 'Patent'),
    'HM': ('NCBI', 'Direct submissions'),
    'HN': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'HO': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'HP': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'HQ': ('NCBI', 'Direct submissions'),
    'HR': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'HS': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'HT': ('DDBJ', 'TPA CON (constructed third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'HU': ('DDBJ', 'TPA CON (constructed third party annotation derived from GenBank primary data, may be DNA or RNA)'),
    'HV': ('DDBJ', 'Patent JPO'),
    'HW': ('DDBJ', 'Patent JPO'),
    'HX': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'HY': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'HZ': ('DDBJ', 'Patent JPO'),
    'I': ('NCBI', 'Patent'),
    'J': ('NCBI', 'LANL Direct submissions'),
    'JA': ('EBI', 'Patent'),
    'JB': ('EBI', 'Patent'),
    'JC': ('EBI', 'Patent'),
    'JD': ('EBI', 'Patent'),
    'JE': ('EBI', 'Patent'),
    'JF': ('NCBI', 'Direct submissions'),
    'JG': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'JH': ('NCBI', 'scaffold/CON'),
    'JI': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JJ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'JK': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'JL': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JM': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'JN': ('NCBI', 'Direct submissions'),
    'JO': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JP': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JQ': ('NCBI', 'Direct submissions'),
    'JR': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JS': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'JT': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JU': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JV': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JW': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'JX': ('NCBI', 'Direct submissions'),
    'JY': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'JZ': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'K': ('NCBI', 'LANL Direct submissions'),
    'KA': ('NCBI', 'TSA (transcriptome shotgun assembly; RNA)'),
    'KB': ('NCBI', 'scaffold/CON'),
    'KC': ('NCBI', 'Direct submissions'),
    'KD': ('NCBI', 'scaffold/CON'),
    'KE': ('NCBI', 'scaffold/CON'),
    'KF': ('NCBI', 'Direct submissions'),
    'KG': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'KH': ('NCBI', 'Patent'),
    'KI': ('NCBI', 'scaffold/CON'),
    'KJ': ('NCBI', 'Direct submissions'),
    'KK': ('NCBI', 'scaffold/CON'),
    'KL': ('NCBI', 'scaffold/CON'),
    'KM': ('NCBI', 'Direct submissions'),
    'KN': ('NCBI', 'scaffold/CON'),
    'KO': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'KP': ('NCBI', 'Direct submissions'),
    'KQ': ('NCBI', 'scaffold/CON'),
    'KR': ('NCBI', 'Direct submissions'),
    'KS': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'KT': ('NCBI', 'Direct submissions'),
    'KU': ('NCBI', 'Direct submissions'),
    'KV': ('NCBI', 'scaffold/CON'),
    'KX': ('NCBI', 'Direct submissions'),
    'KY': ('NCBI', 'Direct submissions'),
    'KZ': ('NCBI', 'scaffold/CON'),
    'L': ('NCBI', 'LANL Direct submissions'),
    'LA': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'LB': ('DDBJ', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'LC': ('DDBJ', 'Direct submissions'),
    'LD': ('DDBJ', 'scaffold/CON'),
    'LE': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'LF': ('DDBJ', 'Patent'),
    'LG': ('DDBJ', 'Patent'),
    'LH': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'LI': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'LJ': ('DDBJ', 'TSA (transcriptome shotgun assembly; RNA)'),
    'LK': ('EBI', 'Direct submissions'),
    'LL': ('EBI', 'Direct submissions'),
    'LM': ('EBI', 'Direct submissions'),
    'LN': ('EBI', 'Direct submissions'),
    'LO': ('EBI', 'Direct submissions'),
    'LP': ('EBI', 'Patent'),
    'LQ': ('EBI', 'Patent'),
    'LR': ('EBI', 'Direct submissions'),
    'LS': ('EBI', 'Direct submissions'),
    'LT': ('EBI', 'Direct submissions'),
    'LU': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'LV': ('DDBJ', 'Patent'),
    'LX': ('DDBJ', 'Patent'),
    'LY': ('DDBJ', 'Patent'),
    'LZ': ('DDBJ', 'Patent'),
    'M': ('NCBI', 'LANL Direct submissions'),
    'MA': ('DDBJ', 'Patent'),
    'MB': ('DDBJ', 'Patent'),
    'MC': ('DDBJ', 'Patent'),
    'MD': ('DDBJ', 'Patent'),
    'ME': ('DDBJ', 'Patent'),
    'MF': ('NCBI', 'Direct submissions'),
    'MG': ('NCBI', 'Direct submissions'),
    'MH': ('NCBI', 'Direct submissions'),
    'MI': ('NCBI', 'Patent'),
    'MJ': ('NCBI', 'GSS (single-pass genomic DNA, i.e. mRNA or other RNA transcript)'),
    'MK': ('NCBI', 'Direct submissions'),
    'ML': ('NCBI', 'scaffold/CON'),
    'MM': ('NCBI', 'Patent'),
    'MN': ('NCBI', 'Direct submissions'),
    'MO': ('NCBI', 'Patent'),
    'MP': ('EBI', 'Patent'),
    'MQ': ('EBI', 'Patent'),
    'MR': ('EBI', 'Patent'),
    'MS': ('EBI', 'Patent'),
    'MT': ('NCBI', 'Direct submissions'),
    'MU': ('NCBI', 'scaffold/CON'),
    'MV': ('NCBI', 'Patent'),
    'MW': ('NCBI', 'Direct submissions'),
    'MX': ('NCBI', 'Patent'),
    'MY': ('NCBI', 'Patent'),
    'MZ': ('NCBI', 'Direct submissions'),
    'N': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'OA': ('EBI', 'Direct submissions'),
    'OB': ('EBI', 'Direct submissions'),
    'OC': ('EBI', 'Direct submissions'),
    'OD': ('EBI', 'Direct submissions'),
    'OE': ('EBI', 'Direct submissions'),
    'OF': ('DDBJ', 'Patent'),
    'OG': ('DDBJ', 'Patent'),
    'OH': ('DDBJ', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'OI': ('DDBJ', 'Patent'),
    'OJ': ('DDBJ', 'Patent'),
    'OK': ('NCBI', 'Direct submissions'),
    'OL': ('NCBI', 'Direct submissions'),
    'OM': ('NCBI', 'Direct submissions'),
    'ON': ('NCBI', 'Direct submissions'),
    'OO': ('NCBI', 'Patent'),
    'OP': ('NCBI', 'Direct submissions'),
    'OQ': ('NCBI', 'Direct submissions'),
    'OR': ('NCBI', 'Direct submissions'),
    'OS': ('NCBI', 'Patent'),
    'OT': ('NCBI', 'Patent'),
    'OU': ('EBI', 'Direct submissions'),
    'OV': ('EBI', 'Direct submissions'),
    'OW': ('EBI', 'Direct submissions'),
    'OX': ('EBI', 'Direct submissions'),
    'OY': ('EBI', 'Direct submissions'),
    'OZ': ('EBI', 'Direct submissions'),
    'PA': ('DDBJ', 'Patent'),
    'PB': ('DDBJ', 'Patent'),
    'PC': ('DDBJ', 'Patent'),
    'PD': ('DDBJ', 'Patent'),
    'PE': ('DDBJ', 'Patent'),
    'PG': ('DDBJ', 'Patent'),
    'PH': ('DDBJ', 'Patent'),
    'PI': ('DDBJ', 'Patent'),
    'PJ': ('DDBJ', 'Patent'),
    'PK': ('DDBJ', 'Patent'),
    'PP': ('NCBI', 'Direct submissions'),
    'PQ': ('NCBI', 'Direct submissions'),
    'PR': ('NCBI', 'Patent'),
    'PRJDA': ('DDBJ via NCBI', 'BioProject'),
    'PRJDB': ('DDBJ', 'BioProject'),
    'PRJEA': ('EBI via NCBI', 'BioProject'),
    'PRJEB': ('EBI', 'BioProject'),
    'PRJNA': ('NCBI', 'BioProject'),
    'PS': ('NCBI', 'scaffold/CON'),
    'PT': ('NCBI', 'Patent'),
    'PU': ('NCBI', 'Patent'),
    'QK': ('EBI', 'Patent'),
    'QL': ('EBI', 'Patent'),
    'QM': ('EBI', 'Patent'),
    'QN': ('EBI', 'Patent'),
    'QO': ('EBI', 'Patent'),
    'R': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'S': ('NCBI', 'Journal Scanning'),
    'SAMD': ('DDBJ', 'BioSample'),
    'SAME': ('EBI', 'BioSample'),
    'SAMN': ('NCBI', 'BioSample'),
    'SRA': ('NCBI', 'SRA (Sequence Read Archive) submissions'),
    'SRP': ('NCBI', 'SRA (Sequence Read Archive) sample'),
    'SRR': ('NCBI', 'SRA (Sequence Read Archive) runs'),
    'SRX': ('NCBI', 'SRA (Sequence Read Archive) experiment'),
    'SRZ': ('NCBI', 'SRA (Sequence Read Archive) analysis object'),
    'T': ('NCBI', 'EST (single-pass cDNA, i.e. mRNA or other RNA transcript)'),
    'U': ('NCBI', 'Direct submissions'),
    'V': ('EBI', 'Direct submissions'),
    'W': ('NCBI', 'EST (previously EBI)'),
    'X': ('EBI', 'Direct submissions'),
    'Y': ('EBI', 'Direct submissions'),
    'Z': ('EBI', 'Direct submissions')
    }

def _letters_to_number(letters: str) -> int:
    alphabet = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14, 'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21, 'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26}
    number = 0
    for i, j in enumerate(letters[::-1]):
        number += alphabet[j] * (10**(i*2))
    return number

class letter_range:
    string: str
    upper_bound: int 
    lower_bound: int 

    def __init__(self, string):
        for i in string:
            assert (i.isalpha() and i.isupper()) or i=='-', print(f'check that {string} is a well-formed letter range')
            
        self.string = string
        self.lower_bound, self.upper_bound = (_letters_to_number(i) for i in string.split('-'))
        
    def __repr__(self):
        return self.string

    def __contains__(self, key: Union[str, int]) -> bool:
        if isinstance(key, str):
            for i in key:
                assert i.isalpha() and i.isupper(), print(f'Key {key} should be a string of upper case letters only')
            key = _letters_to_number(key)
        return self.lower_bound <= key <= self.upper_bound 

_complex_indsc_prefixes = (
    (letter_range('AAA-AZZ'), ('NCBI',  'protein')),
    (letter_range('AAAA-AZZZ'), ('NCBI',  'WGS')),
    (letter_range('AAAAA-AZZZZ'), ('DDBJ',  'MGA')),
    (letter_range('AAAAAA-AZZZZZ'), ('NCBI',  'WGS')),
    (letter_range('BAA-BZZ'), ('DDBJ',  'protein')),
    (letter_range('BAAA-BZZZ'), ('DDBJ',  'WGS')),
    (letter_range('BAAAAA-BZZZZZ'), ('DDBJ',  'WGS')),
    (letter_range('CAA-CZZ'), ('EBI',  'protein')),
    (letter_range('CAAA-CZZZ'), ('EBI',  'WGS')),
    (letter_range('CAAAAA-CZZZZZ'), ('EBI',  'WGS')),
    (letter_range('DAA-DZZ'), ('NCBI',  'TPA or TPA WGS protein')),
    (letter_range('DAAA-DZZZ'), ('NCBI',  'WGS/TSA/TLS TPA')),
    (letter_range('DAAAAA-DZZZZZ'), ('NCBI',  'WGS/TSA/TLS TPA')),
    (letter_range('EAA-EZZ'), ('NCBI',  'WGS protein')),
    (letter_range('EAAA-EZZZ'), ('DDBJ',  'WGS TPA')),
    (letter_range('FAA-FZZ'), ('DDBJ',  'TPA protein')),
    (letter_range('FAAA-FZZZ'), ('EBI',  'WGS')),
    (letter_range('GAA-GZZ'), ('DDBJ',  'WGS protein')),
    (letter_range('GAAA-GZZZ'), ('NCBI',  'TSA (transcriptome shotgun assembly; RNA)')),
    (letter_range('HAA-HZZ'), ('NCBI',  'WGS/TSA TPA protein')),
    (letter_range('HAAA-HZZZ'), ('EBI',  'TSA (transcriptome shotgun assembly; RNA)')),
    (letter_range('IAA-IZZ'), ('DDBJ',  'TPA WGS protein')),
    (letter_range('IAAA-IZZZ'), ('DDBJ',  'TSA (transcriptome shotgun assembly; RNA)')),
    (letter_range('JAA-JZZ'), ('NCBI',  'TSA protein')),
    (letter_range('JAAA-JZZZ'), ('NCBI',  'WGS')),
    (letter_range('JAAAAA-JZZZZZ'), ('NCBI',  'WGS')),
    (letter_range('KAA-KZZ'), ('NCBI',  'WGS protein')),
    (letter_range('KAAA-KZZZ'), ('NCBI',  'TLS')),
    (letter_range('LAA-LZZ'), ('DDBJ',  'TSA/TLS protein')),
    (letter_range('LAAA-LZZZ'), ('NCBI',  'WGS')),
    (letter_range('MAA-MZZ'), ('NCBI',  'WGS/TSA protein')),
    (letter_range('MAAA-MZZZ'), ('NCBI',  'WGS')),
    (letter_range('NAA-NZZ'), ('NCBI',  'WGS/TSA protein')),
    (letter_range('NAAA-NZZZ'), ('NCBI',  'WGS')),
    (letter_range('OAA-OZZ'), ('NCBI',  'WGS protein')),
    (letter_range('OAAA-OZZZ'), ('EBI',  'WGS')),
    (letter_range('PAA-PZZ'), ('NCBI',  'WGS protein')),
    (letter_range('PAAA-PZZZ'), ('NCBI',  'WGS')),
    (letter_range('QAA-QZZ'), ('NCBI',  'protein')),
    (letter_range('QAAA-QZZZ'), ('NCBI',  'WGS')),
    (letter_range('RAA-RZZ'), ('NCBI',  'WGS protein')),
    (letter_range('RAAA-RZZZ'), ('NCBI',  'WGS')),
    (letter_range('SAA-SZZ'), ('EBI',  'protein')),
    (letter_range('SAAA-SZZZ'), ('NCBI',  'WGS')),
    (letter_range('TAA-TZZ'), ('NCBI',  'WGS protein')),
    (letter_range('TAAA-TZZZ'), ('DDBJ',  'TLS')),
    (letter_range('UAA-UZZ'), ('NCBI',  'protein')),
    (letter_range('UAAA-UZZZ'), ('EBI',  'WGS')),
    (letter_range('VAA-VZZ'), ('EBI',  'protein')),
    (letter_range('VAAA-VZZZ'), ('NCBI',  'WGS')),
    (letter_range('WAA-WZZ'), ('NCBI',  'protein')),
    (letter_range('WAAA-WZZZ'), ('NCBI',  'WGS')),
    (letter_range('XAA-XZZ'), ('NCBI',  'protein')),
    (letter_range('XAAA-XZZZ'), ('NCBI',  'WGS')),
    (letter_range('YAAA-YZZZ'), ('DDBJ',  'TSA TPA')),
    (letter_range('ZAAA-ZZZZ'), ('DDBJ',  'TLS TPA'))
    )

def annotate_from_accession(accession: str) -> tuple:
    """The prefixes of Refseq IDs and INDSC accession numbers indicate their source and
    some characteristics of the molecules they refer to. Using tables from RefSeq and INDSC,
    this function accepts an accession ID and returns a tuple of their relevant annotations."""
    
    if '_' in accession:
        return _refseq_prefixes[accession[:3]]
    
    for i, j in enumerate(accession):
        if j.isdigit():
            digits = i
            break
        
    prefix = accession[:digits]
    if prefix in _simple_INDSC_prefixes:
        return _simple_INDSC_prefixes[prefix]
    
    for i in _complex_indsc_prefixes:
        if prefix in i[0]:
            return i[1]
